image: google/cloud-sdk:alpine

stages:
  - bucket_creation
  - validate
  - plan
  - apply
  - destroy

variables:
  TF_IN_AUTOMATION: "true"
  TF_INPUT: "false"
  TF_REGION: ${REGION}
  GOOGLE_PROJECT: ${PROJECT_ID}
  GOOGLE_PROJECT_NUMBER: ${PROJECT_NUMBER}
  GOOGLE_SERVICE_ACCOUNT: masterclass-sa-gitlab@${PROJECT_ID}.iam.gserviceaccount.com
  WORKLOAD_IDENTITY_PROVIDER: projects/${PROJECT_NUMBER}/locations/global/workloadIdentityPools/gitlab-pool/providers/gitlab-provider

.id_tokens:
  id_tokens:
    GITLAB_OIDC_TOKEN:
      aud: https://gitlab.com


before_script:
  # -----------------------------
  # Install dependencies
  # -----------------------------
  - apk add --no-cache bash curl unzip python3 py3-pip
  - python3 -m venv venv
  - source venv/bin/activate
  - pip install --upgrade pip
  - pip install google-cloud-storage

  # -----------------------------
  # Install Terraform
  # -----------------------------
  - curl -LO https://releases.hashicorp.com/terraform/1.6.0/terraform_1.6.0_linux_amd64.zip
  - unzip -o terraform_1.6.0_linux_amd64.zip
  - mv terraform /usr/local/bin/
  - terraform version

bucket_creation:
  stage: bucket_creation
  extends: .id_tokens
  # -----------------------------
  # Authenticate to GCP via Workload Identity Federation
  # -----------------------------
  script:
    - echo ${GITLAB_OIDC_TOKEN} > .ci_job_jwt_file
    - gcloud iam workload-identity-pools create-cred-config ${WORKLOAD_IDENTITY_PROVIDER}
        --service-account="${GOOGLE_SERVICE_ACCOUNT}"
        --output-file=.gcp_temp_cred.json
        --credential-source-file=.ci_job_jwt_file
    - gcloud auth login --cred-file=`pwd`/.gcp_temp_cred.json
    - export GOOGLE_APPLICATION_CREDENTIALS=$(pwd)/.gcp_temp_cred.json
    - gcloud auth list

  # -----------------------------
  # Create backend bucket if not exists
  # -----------------------------
    - chmod +x $CI_PROJECT_DIR/terraform_project/scripts/backend_bucket/create_backend_bucket.sh
    - $CI_PROJECT_DIR/terraform_project/scripts/backend_bucket/create_backend_bucket.sh ${TF_STATE_BUCKET}

  # -----------------------------
  # Terraform init
  # -----------------------------
    - cd "$CI_PROJECT_DIR/$TF_ROOT"
    - terraform init -backend-config="bucket=$TF_STATE_BUCKET"

# -----------------------------
# Terraform validate
# -----------------------------
validate:
  stage: validate
  script:
    - terraform fmt -check
    - terraform validate

# -----------------------------
# Terraform plan
# -----------------------------
plan:
  stage: plan
  script:
    - terraform plan -out=tfplan
  artifacts:
    paths:
      - tfplan
  only:
    - merge_requests

# -----------------------------
# Terraform apply
# -----------------------------
apply:
  stage: apply
  extends: .id_tokens
  dependencies:
    - plan
  script:
    # Re-authenticate in case of a new runner
    - echo ${GITLAB_OIDC_TOKEN} > .ci_job_jwt_file
    - gcloud iam workload-identity-pools create-cred-config ${WORKLOAD_IDENTITY_PROVIDER}
      --service-account="${GOOGLE_SERVICE_ACCOUNT}"
      --output-file=.gcp_temp_cred.json
      --credential-source-file=.ci_job_jwt_file
    - gcloud auth login --cred-file=`pwd`/.gcp_temp_cred.json
    - gcloud auth list

    - terraform apply -auto-approve tfplan
  only:
    - main

# -----------------------------
# Terraform destroy
# -----------------------------
destroy:
  stage: destroy
  extends: .id_tokens
  script:
    # Re-authenticate in case of a new runner
    - echo ${GITLAB_OIDC_TOKEN} > .ci_job_jwt_file
    - gcloud iam workload-identity-pools create-cred-config ${WORKLOAD_IDENTITY_PROVIDER}
      --service-account="${GOOGLE_SERVICE_ACCOUNT}"
      --output-file=.gcp_temp_cred.json
      --credential-source-file=.ci_job_jwt_file
    - gcloud auth login --cred-file=`pwd`/.gcp_temp_cred.json
    - gcloud auth list

    - terraform destroy -auto-approve
  when: manual
  only:
    - main