main:
  params: [event]
  steps:

    - init:
        assign:
          - bucket: $${event.data.bucket}
          - file_name: $${event.data.name}
          - project_id: $${sys.get_env("GOOGLE_CLOUD_PROJECT_ID")}
          - dataset: "${bq_dataset}"
          - table: "${bq_table}"
          - location: "${location}"
          - job_name: "${job_name}"

    - load_csv_to_bigquery:
        call: googleapis.bigquery.v2.jobs.insert
        args:
          projectId: $${project_id}
          body:
            configuration:
              load:
                sourceUris: $${"gs://" + bucket + "/" + file_name}
                destinationTable:
                  projectId: $${project_id}
                  datasetId: $${dataset}
                  tableId: $${table}
                sourceFormat: "CSV"
                skipLeadingRows: 1
                autodetect: true
                writeDisposition: "WRITE_TRUNCATE"
        result: bq_job

    - wait_for_bq:
        call: googleapis.bigquery.v2.jobs.get
        args:
          projectId: $${project_id}
          jobId: $${bq_job.jobReference.jobId}
          location: $${location}
        
        result: bq_status

    - check_bq:
        switch:
          - condition: $${bq_status.status.state == "DONE"}
            next: trigger_cloud_run_job
        next: wait_for_bq

    - trigger_cloud_run_job:
        call: googleapis.run.v1.namespaces.jobs.run
        args:
          name: $${"namespaces/" + project_id + "/jobs/" + job_name}
          location: $${location}
        result: job_result

    - done:
        return:
          bq_job_id: $${bq_job.jobReference.jobId}
          job_execution: $${job_result.metadata.name}